# Generated by Django 3.0.3 on 2020-05-16 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Selection",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(default="Passed Test (Awaiting)", max_length=20)),
                ("draw_rank", models.IntegerField(default=None, null=True)),
                ("payment_value", models.FloatField(default=None, null=True)),
                ("ticket_type", models.CharField(default=None, max_length=25, null=True)),
                ("payment_due_date", models.DateTimeField(default=None, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SelectionLogs",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event", models.CharField(editable=False, max_length=20)),
                ("message", models.TextField(editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "selection",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="selection.Selection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SelectionDocument",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_location", models.TextField()),
                (
                    "doc_type",
                    models.CharField(
                        choices=[("payment_proof", "Payment Proof"), ("student_id", "Student ID")], max_length=20
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "selection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="selection.Selection"
                    ),
                ),
            ],
        ),
    ]
