# Generated by Django 3.0.6 on 2020-06-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("selection", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="selection",
            name="status",
            field=models.CharField(default="Passed Test (Awaiting)", max_length=40),
        ),
        migrations.AlterField(
            model_name="selection", name="ticket_type", field=models.CharField(default=None, max_length=40, null=True)
        ),
    ]
