# Generated by Django 3.0.3 on 2020-05-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("selected", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="passedcandidate", name="draw_rank", field=models.IntegerField(default=None, null=True)
        )
    ]
