# Generated by Django 3.0.3 on 2020-05-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("profiles", "0002_auto_20200207_2305")]

    operations = [
        migrations.AddField(model_name="profile", name="company", field=models.CharField(default="", max_length=40))
    ]
