# Generated by Django 3.0.6 on 2020-05-22 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("profiles", "0003_profile_company")]

    operations = [
        migrations.AlterField(model_name="profile", name="gender", field=models.CharField(max_length=25)),
        migrations.AlterField(model_name="profile", name="ticket_type", field=models.CharField(max_length=25)),
    ]
