# Generated by Django 3.0.6 on 2020-05-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("profiles", "0004_auto_20200522_2331")]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="id_card_location",
            field=models.CharField(default=None, max_length=200, null=True),
        )
    ]
