# Generated by Django 3.0.6 on 2020-05-27 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("profiles", "0005_profile_id_card_location")]

    operations = [migrations.RemoveField(model_name="profile", name="id_card_location")]
