# Generated by Django 3.0.6 on 2020-06-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("profiles", "0006_remove_profile_id_card_location")]

    operations = [
        migrations.AlterField(model_name="profile", name="company", field=models.CharField(default="", max_length=100))
    ]
