# Generated by Django 3.0.3 on 2020-02-14 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("applications", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("submission_type", models.CharField(max_length=20)),
                ("file_location", models.TextField()),
                ("score", models.IntegerField(default=0)),
                ("feedback_location", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="applications.Application",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="CodingTestSubmission"),
    ]
