# Generated by Django 3.0.3 on 2020-05-09 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("applications", "0004_auto_20200301_1823")]

    operations = [
        migrations.RemoveField(model_name="application", name="slu01_started_at"),
        migrations.RemoveField(model_name="application", name="slu02_started_at"),
        migrations.RemoveField(model_name="application", name="slu03_started_at"),
    ]
