# Generated by Django 3.0.2 on 2020-02-03 00:08

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "uuid",
                    models.CharField(
                        default=users.models.get_default_uuid, editable=False, max_length=32, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"abstract": False},
        )
    ]
