# Generated by Django 3.0.3 on 2020-02-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial")]

    operations = [migrations.AddField(model_name="user", name="is_staff", field=models.BooleanField(default=False))]
