# Generated by Django 3.0.3 on 2020-02-15 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0003_auto_20200215_1844")]

    operations = [migrations.RenameModel(old_name="UserRecoverPassword", new_name="UserResetPassword")]
