# Generated by Django 3.0.3 on 2020-03-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0004_auto_20200215_2052")]

    operations = [
        migrations.AddField(
            model_name="user", name="code_of_conduct_accepted", field=models.BooleanField(default=False)
        )
    ]
