# Generated by Django 3.0.3 on 2020-05-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0005_user_code_of_conduct_accepted")]

    operations = [migrations.AddField(model_name="user", name="is_admin", field=models.BooleanField(default=False))]
