# Generated by Django 3.0.3 on 2020-03-01 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.FloatField()),
                ("currency", models.CharField(choices=[("eur", "€")], max_length=10)),
                ("due_date", models.DateTimeField()),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[("student", "Student"), ("regular", "Regular"), ("company", "Company")], max_length=15
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting_for_documents", "Waiting for candidate documents"),
                            ("pending_verification", "Pending verification"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="waiting_for_documents",
                        max_length=30,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_location", models.TextField()),
                (
                    "doc_type",
                    models.CharField(
                        choices=[("payment_proof", "Payment Proof"), ("student_id", "Student ID")], max_length=20
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="payments.Payment"
                    ),
                ),
            ],
        ),
    ]
