# Generated by Django 3.0.3 on 2020-02-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("payments", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="doc_type",
            field=models.CharField(
                choices=[("payment_proof", "Payment Proof"), ("student_id", "Student ID")], max_length=20
            ),
        )
    ]
