# Generated by Django 3.0.3 on 2020-05-10 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("payments", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="PaymentLogs",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event", models.CharField(editable=False, max_length=20)),
                ("message", models.TextField(editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="payments.Payment",
                    ),
                ),
            ],
        )
    ]
