# Generated by Django 3.0.3 on 2020-02-15 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("payments", "0002_auto_20200215_1730")]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting_for_documents", "Waiting for candidate documents"),
                    ("pending_verification", "Pending verification"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="waiting_for_documents",
                max_length=30,
            ),
        )
    ]
